services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-database
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
  

  authentication-service:
    build:
      context: ../authentication-service
    ports:
      - "8083:8080"
    depends_on:
      auth-db:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
    

  tracking-db:
    image: postgres:16-alpine
    container_name: tracking-database
    environment:
      POSTGRES_USER: trackinguser
      POSTGRES_PASSWORD: trackingpassword
      POSTGRES_DB: tracking_db
    volumes:
      - tracking_data:/var/lib/postgresql/data
    

  tracking-service:
    build:
      context: ../tracking-service
    ports:
      - "8082:8080"
    depends_on:
      tracking-db:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
    

volumes:
  auth_pg_data:
  tracking_data: